name: stagexl
version: 0.8.0
author: Bernhard Pichler <support@stagexl.org>
description: A library for graphically rich content like games, based on the Flash API.
homepage: http://www.stagexl.org
dependencies:
  browser: any
  meta: any
dev_dependencies:
  unittest: any
