name: dartflash
<<<<<<< HEAD
version: 0.6.4
author: Bernhard Pichler <support@dartflash.com>
description: You are an Adobe Flash developer? Check out this package and see how easy it is to bring your Flash skills to DART and HTML5. The dartflash library provides the familiar Flash API - work with Sprites, Bitmaps, TextFields and even Sounds like you did with Flash before. Please visit www.dartflash.com for more information and demos.
homepage: http://www.dartflash.com
dependencies:
  browser: any
  
=======
version: 0.6.5
author: Bernhard Pichler <support@dartflash.com>
description: A library for graphically rich content like games, based on the Flash API.
homepage: http://www.dartflash.com
dependencies:
  browser: any
>>>>>>> latest
