name: stagexl
version: 0.8.8
author: Bernhard Pichler <support@stagexl.org>
description: A library for graphically rich content like games, based on the Flash API.
homepage: http://www.stagexl.org
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
